Addition of 2 vectors

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
V1= np.array([1,2,3,4])
V2=np.array([3,2,5,4])
Vector_add = V1+V2
Vector_add

array([4, 4, 8, 8])

Matrix Addition

In [3]:
A= np.array([[1,2],[3,4],[5,6,],[7,8]])
B=np.array([[2,2],[4,4],[6,6,],[7,8]])
c = A+B
c

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [14, 16]])

Tensor addition

In [4]:
T1 = tf.constant ([[1,2],[3,4],[5,6,],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6,],[9,8]])
tensor_add= T1+T2
tensor_add

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  4],
       [ 8,  8],
       [12, 12],
       [16, 16]], dtype=int32)>