Multiplication of 2 matrix

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
A= np.array([[1,2],[3,4],[5,6,],[7,8]])
B=np.array([[2,2],[4,4],[6,6,],[7,8]])
c = A*B
c


array([[ 2,  4],
       [12, 16],
       [30, 36],
       [49, 64]])

Vector Multiplication

In [3]:
V1= np.array([1,2,3,4])
V2=np.array([3,2,5,4])
Vector_multiplication = V1*V2
Vector_multiplication


array([ 3,  4, 15, 16])

Tensor Multiplication

In [4]:
T1 = tf.constant ([[1,2],[3,4],[5,6,],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6,],[9,8]])
tensor_multiplication= T1*T2
tensor_multiplication


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [15, 16],
       [35, 36],
       [63, 64]], dtype=int32)>